export interface StockMasterItem {
  code: string;
  name: string;
  market: "KS" | "KQ";
  type: "regular" | "preferred" | "etf" | "spac";
}

export const STOCK_MASTER: StockMasterItem[] = [
  // ── KOSPI regular ────────────────────────────────────────────────────────
  { code: "005930", name: "삼성전자",           market: "KS", type: "regular" },
  { code: "000660", name: "SK하이닉스",         market: "KS", type: "regular" },
  { code: "005380", name: "현대차",             market: "KS", type: "regular" },
  { code: "000270", name: "기아",               market: "KS", type: "regular" },
  { code: "035420", name: "NAVER",              market: "KS", type: "regular" },
  { code: "035720", name: "카카오",             market: "KS", type: "regular" },
  { code: "051910", name: "LG화학",             market: "KS", type: "regular" },
  { code: "207940", name: "삼성바이오로직스",   market: "KS", type: "regular" },
  { code: "005490", name: "POSCO홀딩스",        market: "KS", type: "regular" },
  { code: "006400", name: "삼성SDI",            market: "KS", type: "regular" },
  { code: "068270", name: "셀트리온",           market: "KS", type: "regular" },
  { code: "096770", name: "SK이노베이션",       market: "KS", type: "regular" },
  { code: "034730", name: "SK스퀘어",           market: "KS", type: "regular" },
  { code: "003550", name: "LG",                 market: "KS", type: "regular" },
  { code: "012330", name: "현대모비스",         market: "KS", type: "regular" },
  { code: "009150", name: "삼성전기",           market: "KS", type: "regular" },
  { code: "042700", name: "한미반도체",         market: "KS", type: "regular" },
  { code: "055550", name: "신한지주",           market: "KS", type: "regular" },
  { code: "105560", name: "KB금융",             market: "KS", type: "regular" },
  { code: "086790", name: "하나금융지주",       market: "KS", type: "regular" },
  { code: "032830", name: "삼성생명",           market: "KS", type: "regular" },
  { code: "066570", name: "LG전자",             market: "KS", type: "regular" },
  { code: "028260", name: "삼성물산",           market: "KS", type: "regular" },
  { code: "000810", name: "삼성화재",           market: "KS", type: "regular" },
  { code: "003600", name: "SK",                 market: "KS", type: "regular" },
  { code: "011200", name: "HMM",                market: "KS", type: "regular" },
  { code: "010130", name: "고려아연",           market: "KS", type: "regular" },
  { code: "018260", name: "삼성SDS",            market: "KS", type: "regular" },
  { code: "003490", name: "대한항공",           market: "KS", type: "regular" },
  { code: "011070", name: "LG이노텍",           market: "KS", type: "regular" },
  { code: "078930", name: "GS",                 market: "KS", type: "regular" },
  { code: "033780", name: "KT&G",               market: "KS", type: "regular" },
  { code: "010950", name: "S-Oil",              market: "KS", type: "regular" },
  { code: "036570", name: "엔씨소프트",         market: "KS", type: "regular" },
  { code: "090430", name: "아모레퍼시픽",       market: "KS", type: "regular" },
  { code: "024110", name: "기업은행",           market: "KS", type: "regular" },
  { code: "097950", name: "CJ제일제당",         market: "KS", type: "regular" },
  { code: "019170", name: "신세계",             market: "KS", type: "regular" },
  { code: "047050", name: "포스코인터내셔널",   market: "KS", type: "regular" },
  { code: "161390", name: "한국타이어앤테크놀로지", market: "KS", type: "regular" },
  { code: "316140", name: "우리금융지주",       market: "KS", type: "regular" },
  { code: "032640", name: "LG유플러스",         market: "KS", type: "regular" },
  { code: "030200", name: "KT",                 market: "KS", type: "regular" },
  { code: "017670", name: "SK텔레콤",           market: "KS", type: "regular" },
  { code: "015760", name: "한국전력",           market: "KS", type: "regular" },
  { code: "042660", name: "한화오션",           market: "KS", type: "regular" },
  { code: "010140", name: "삼성중공업",         market: "KS", type: "regular" },
  { code: "012450", name: "한화에어로스페이스", market: "KS", type: "regular" },
  { code: "003620", name: "KG모빌리티",         market: "KS", type: "regular" },
  { code: "018880", name: "한온시스템",         market: "KS", type: "regular" },
  { code: "329180", name: "HD현대중공업",       market: "KS", type: "regular" },
  { code: "267250", name: "HD현대",             market: "KS", type: "regular" },
  { code: "028050", name: "삼성E&A",            market: "KS", type: "regular" },
  { code: "009830", name: "한화솔루션",         market: "KS", type: "regular" },
  { code: "003670", name: "포스코퓨처엠",       market: "KS", type: "regular" },
  { code: "034020", name: "두산에너빌리티",     market: "KS", type: "regular" },
  { code: "064350", name: "현대로템",           market: "KS", type: "regular" },
  { code: "086280", name: "현대글로비스",       market: "KS", type: "regular" },
  { code: "000720", name: "현대건설",           market: "KS", type: "regular" },
  { code: "047810", name: "한국항공우주",       market: "KS", type: "regular" },
  { code: "000100", name: "유한양행",           market: "KS", type: "regular" },
  { code: "241560", name: "두산밥캣",           market: "KS", type: "regular" },
  { code: "010620", name: "HD현대미포",         market: "KS", type: "regular" },
  { code: "004020", name: "현대제철",           market: "KS", type: "regular" },
  { code: "011790", name: "SKC",                market: "KS", type: "regular" },
  { code: "088350", name: "한화생명",           market: "KS", type: "regular" },
  { code: "071050", name: "한국금융지주",       market: "KS", type: "regular" },
  { code: "023530", name: "롯데쇼핑",           market: "KS", type: "regular" },
  { code: "004990", name: "롯데지주",           market: "KS", type: "regular" },
  { code: "000150", name: "두산",               market: "KS", type: "regular" },
  { code: "007070", name: "GS리테일",           market: "KS", type: "regular" },
  { code: "002790", name: "아모레G",            market: "KS", type: "regular" },
  { code: "006280", name: "녹십자",             market: "KS", type: "regular" },
  { code: "018010", name: "효성",               market: "KS", type: "regular" },
  { code: "001040", name: "CJ",                 market: "KS", type: "regular" },
  { code: "021240", name: "코웨이",             market: "KS", type: "regular" },
  { code: "000080", name: "하이트진로",         market: "KS", type: "regular" },
  { code: "138040", name: "메리츠금융지주",     market: "KS", type: "regular" },
  { code: "139130", name: "DGB금융지주",        market: "KS", type: "regular" },
  { code: "005830", name: "DB손해보험",         market: "KS", type: "regular" },
  { code: "014680", name: "한솔케미칼",         market: "KS", type: "regular" },
  { code: "009540", name: "한국조선해양",       market: "KS", type: "regular" },
  { code: "002380", name: "KCC",                market: "KS", type: "regular" },
  { code: "298040", name: "효성중공업",         market: "KS", type: "regular" },
  { code: "192820", name: "코스맥스",           market: "KS", type: "regular" },
  { code: "298050", name: "효성첨단소재",       market: "KS", type: "regular" },
  { code: "010060", name: "OCI홀딩스",          market: "KS", type: "regular" },
  { code: "034310", name: "NICE",               market: "KS", type: "regular" },
  { code: "051600", name: "한전기술",           market: "KS", type: "regular" },
  { code: "178920", name: "PI첨단소재",         market: "KS", type: "regular" },
  { code: "003410", name: "쌍용씨앤이",         market: "KS", type: "regular" },
  { code: "036460", name: "한국가스공사",       market: "KS", type: "regular" },
  { code: "001680", name: "대상",               market: "KS", type: "regular" },
  { code: "006800", name: "미래에셋증권",       market: "KS", type: "regular" },
  { code: "033640", name: "한국콜마",           market: "KS", type: "regular" },
  { code: "030000", name: "제일기획",           market: "KS", type: "regular" },
  { code: "011170", name: "롯데케미칼",         market: "KS", type: "regular" },
  { code: "009540", name: "한국조선해양",       market: "KS", type: "regular" },
  { code: "003230", name: "삼양식품",           market: "KS", type: "regular" },
  { code: "079550", name: "LIG넥스원",          market: "KS", type: "regular" },
  { code: "128940", name: "한미약품",           market: "KS", type: "regular" },
  { code: "011210", name: "현대위아",           market: "KS", type: "regular" },
  { code: "028670", name: "팬오션",             market: "KS", type: "regular" },
  { code: "047040", name: "대우건설",           market: "KS", type: "regular" },
  { code: "375500", name: "DL이앤씨",           market: "KS", type: "regular" },
  { code: "294870", name: "HDC현대산업개발",    market: "KS", type: "regular" },
  { code: "030750", name: "KT서브마린",         market: "KS", type: "regular" },
  { code: "023590", name: "다우기술",           market: "KS", type: "regular" },
  { code: "011690", name: "LS",                 market: "KS", type: "regular" },
  { code: "010120", name: "LS ELECTRIC",        market: "KS", type: "regular" },
  { code: "006260", name: "LS",                 market: "KS", type: "regular" },
  { code: "000990", name: "DB하이텍",           market: "KS", type: "regular" },
  { code: "012630", name: "HDC",                market: "KS", type: "regular" },
  { code: "004170", name: "신세계I&C",          market: "KS", type: "regular" },
  { code: "020150", name: "롯데에너지머티리얼즈", market: "KS", type: "regular" },
  { code: "016360", name: "삼성증권",           market: "KS", type: "regular" },
  { code: "006360", name: "GS건설",             market: "KS", type: "regular" },
  { code: "004800", name: "효성",               market: "KS", type: "regular" },
  { code: "000670", name: "영풍",               market: "KS", type: "regular" },
  { code: "001800", name: "오리온홀딩스",       market: "KS", type: "regular" },
  { code: "271560", name: "오리온",             market: "KS", type: "regular" },
  { code: "003490", name: "대한항공",           market: "KS", type: "regular" },
  { code: "028260", name: "삼성물산",           market: "KS", type: "regular" },
  { code: "007310", name: "오뚜기",             market: "KS", type: "regular" },
  { code: "008770", name: "호텔신라",           market: "KS", type: "regular" },
  { code: "004130", name: "이수화학",           market: "KS", type: "regular" },
  { code: "023530", name: "롯데쇼핑",           market: "KS", type: "regular" },
  { code: "000210", name: "DL",                 market: "KS", type: "regular" },
  { code: "009240", name: "한샘",               market: "KS", type: "regular" },
  { code: "010140", name: "삼성중공업",         market: "KS", type: "regular" },
  { code: "011780", name: "금호석유화학",       market: "KS", type: "regular" },
  { code: "003490", name: "대한항공",           market: "KS", type: "regular" },
  { code: "005940", name: "NH투자증권",         market: "KS", type: "regular" },
  { code: "016880", name: "웅진",               market: "KS", type: "regular" },
  { code: "088790", name: "화승엔터프라이즈",   market: "KS", type: "regular" },
  { code: "091390", name: "국도화학",           market: "KS", type: "regular" },
  { code: "018880", name: "한온시스템",         market: "KS", type: "regular" },
  { code: "013570", name: "디와이",             market: "KS", type: "regular" },
  { code: "002630", name: "오리엔트바이오",     market: "KS", type: "regular" },
  { code: "015020", name: "이스타코",           market: "KS", type: "regular" },
  { code: "003460", name: "유화증권",           market: "KS", type: "regular" },
  { code: "002300", name: "농심",               market: "KS", type: "regular" },
  { code: "003960", name: "사조대림",           market: "KS", type: "regular" },
  { code: "004140", name: "동방아그로",         market: "KS", type: "regular" },
  { code: "007460", name: "에이프로젠제약",     market: "KS", type: "regular" },
  { code: "036490", name: "SK케미칼",           market: "KS", type: "regular" },
  { code: "002720", name: "국제약품",           market: "KS", type: "regular" },
  { code: "004890", name: "동일방직",           market: "KS", type: "regular" },
  { code: "004310", name: "현대약품",           market: "KS", type: "regular" },
  { code: "006980", name: "우성사료",           market: "KS", type: "regular" },
  { code: "007280", name: "에이텍",             market: "KS", type: "regular" },
  { code: "023460", name: "쌍방울",             market: "KS", type: "regular" },
  // 추가 KOSPI — 누락 종목 보완
  { code: "039490", name: "키움증권",           market: "KS", type: "regular" },
  { code: "084690", name: "대상홀딩스",         market: "KS", type: "regular" },
  { code: "001440", name: "대한전선",           market: "KS", type: "regular" },
  { code: "007700", name: "F&F홀딩스",         market: "KS", type: "regular" },
  { code: "007390", name: "네이처셀",           market: "KS", type: "regular" },
  { code: "005940", name: "NH투자증권",         market: "KS", type: "regular" },
  { code: "003530", name: "대한제강",           market: "KS", type: "regular" },
  { code: "001045", name: "CJ우",              market: "KS", type: "preferred" },
  { code: "008770", name: "호텔신라",           market: "KS", type: "regular" },
  { code: "071840", name: "롯데하이마트",       market: "KS", type: "regular" },
  { code: "271560", name: "오리온",             market: "KS", type: "regular" },
  { code: "007310", name: "오뚜기",             market: "KS", type: "regular" },
  { code: "006650", name: "대한유화",           market: "KS", type: "regular" },
  { code: "005945", name: "NH농협금융지주",     market: "KS", type: "regular" },
  { code: "001210", name: "금호전기",           market: "KS", type: "regular" },
  { code: "024720", name: "콜마비앤에이치",     market: "KS", type: "regular" },
  { code: "010955", name: "S-Oil우",           market: "KS", type: "preferred" },
  { code: "055490", name: "OCI",               market: "KS", type: "regular" },
  { code: "016880", name: "웅진",               market: "KS", type: "regular" },

  // ── KOSPI preferred ──────────────────────────────────────────────────────
  { code: "005935", name: "삼성전자우",         market: "KS", type: "preferred" },
  { code: "005385", name: "현대차2우B",         market: "KS", type: "preferred" },
  { code: "000270", name: "기아우",             market: "KS", type: "preferred" },
  { code: "006405", name: "삼성SDI우",          market: "KS", type: "preferred" },
  { code: "090435", name: "아모레퍼시픽우",     market: "KS", type: "preferred" },
  { code: "051915", name: "LG화학우",           market: "KS", type: "preferred" },
  { code: "207941", name: "삼성바이오로직스우", market: "KS", type: "preferred" },

  // ── KOSDAQ regular ───────────────────────────────────────────────────────
  { code: "247540", name: "에코프로비엠",       market: "KQ", type: "regular" },
  { code: "086520", name: "에코프로",           market: "KQ", type: "regular" },
  { code: "196170", name: "알테오젠",           market: "KQ", type: "regular" },
  { code: "357780", name: "솔브레인",           market: "KQ", type: "regular" },
  { code: "263750", name: "펄어비스",           market: "KQ", type: "regular" },
  { code: "145020", name: "휴젤",               market: "KQ", type: "regular" },
  { code: "214150", name: "클래시스",           market: "KQ", type: "regular" },
  { code: "041510", name: "SM엔터",             market: "KQ", type: "regular" },
  { code: "035900", name: "JYP엔터",            market: "KQ", type: "regular" },
  { code: "122870", name: "와이지엔터",         market: "KQ", type: "regular" },
  { code: "091990", name: "셀트리온헬스케어",   market: "KQ", type: "regular" },
  { code: "005290", name: "동진쎄미켐",         market: "KQ", type: "regular" },
  { code: "059270", name: "해성디에스",         market: "KQ", type: "regular" },
  { code: "112040", name: "위메이드",           market: "KQ", type: "regular" },
  { code: "220100", name: "퓨처켐",             market: "KQ", type: "regular" },
  { code: "039030", name: "이오테크닉스",       market: "KQ", type: "regular" },
  { code: "068760", name: "셀트리온제약",       market: "KQ", type: "regular" },
  { code: "293490", name: "카카오게임즈",       market: "KQ", type: "regular" },
  { code: "067310", name: "하나마이크론",       market: "KQ", type: "regular" },
  { code: "036810", name: "에프에스티",         market: "KQ", type: "regular" },
  { code: "183300", name: "코미팜",             market: "KQ", type: "regular" },
  { code: "048260", name: "오스템임플란트",     market: "KQ", type: "regular" },
  { code: "376300", name: "디어유",             market: "KQ", type: "regular" },
  { code: "010170", name: "대한광통신",         market: "KQ", type: "regular" },
  { code: "278470", name: "에이피알",           market: "KQ", type: "regular" },
  { code: "277810", name: "레인보우로보틱스",   market: "KQ", type: "regular" },
  { code: "108380", name: "로보티즈",           market: "KQ", type: "regular" },
  { code: "095660", name: "네오위즈",           market: "KQ", type: "regular" },
  { code: "053800", name: "안랩",               market: "KQ", type: "regular" },
  { code: "042600", name: "네오팜",             market: "KQ", type: "regular" },
  { code: "035760", name: "CJ ENM",             market: "KQ", type: "regular" },
  { code: "095340", name: "ISC",                market: "KQ", type: "regular" },
  { code: "256940", name: "킹넷",               market: "KQ", type: "regular" },
  { code: "073010", name: "케어젠",             market: "KQ", type: "regular" },
  { code: "094360", name: "칩스앤미디어",       market: "KQ", type: "regular" },
  { code: "079940", name: "가비아",             market: "KQ", type: "regular" },
  { code: "053350", name: "이니텍",             market: "KQ", type: "regular" },
  { code: "178320", name: "서진시스템",         market: "KQ", type: "regular" },
  { code: "310210", name: "보로노이",           market: "KQ", type: "regular" },
  { code: "226950", name: "올릭스",             market: "KQ", type: "regular" },
  { code: "028300", name: "에이치엘비",         market: "KQ", type: "regular" },
  { code: "239340", name: "이녹스첨단소재",     market: "KQ", type: "regular" },
  { code: "064760", name: "티씨케이",           market: "KQ", type: "regular" },
  { code: "058470", name: "리노공업",           market: "KQ", type: "regular" },
  { code: "257720", name: "실리콘투",           market: "KQ", type: "regular" },
  { code: "041440", name: "현대와이솔",         market: "KQ", type: "regular" },
  { code: "090460", name: "비에이치",           market: "KQ", type: "regular" },
  { code: "308920", name: "사람인에이치알",     market: "KQ", type: "regular" },
  { code: "319400", name: "현대무벡스",         market: "KQ", type: "regular" },
  { code: "060260", name: "에이치피오",         market: "KQ", type: "regular" },
  { code: "300060", name: "이노뎁",             market: "KQ", type: "regular" },
  { code: "035420", name: "NAVER",              market: "KQ", type: "regular" },
  { code: "048550", name: "대진첨단소재",       market: "KQ", type: "regular" },
  { code: "039310", name: "NIBEC",              market: "KQ", type: "regular" },
  { code: "300720", name: "한양이엔지",         market: "KQ", type: "regular" },
  { code: "040510", name: "에스피에이",         market: "KQ", type: "regular" },
  { code: "109820", name: "엔케이맥스",         market: "KQ", type: "regular" },
  { code: "066920", name: "코오롱티슈진",       market: "KQ", type: "regular" },
  { code: "036890", name: "진성티이씨",         market: "KQ", type: "regular" },
  { code: "037270", name: "YG PLUS",            market: "KQ", type: "regular" },
  { code: "066790", name: "씨씨에스",           market: "KQ", type: "regular" },
  { code: "067900", name: "에스엔에스에섹",     market: "KQ", type: "regular" },
  { code: "204270", name: "우리기술투자",       market: "KQ", type: "regular" },
  { code: "335890", name: "비에이치아이",       market: "KQ", type: "regular" },
  { code: "300060", name: "이노뎁",             market: "KQ", type: "regular" },
  { code: "200350", name: "슈프리마홀딩스",     market: "KQ", type: "regular" },
  { code: "142760", name: "하이코리아",         market: "KQ", type: "regular" },
  { code: "106820", name: "재영솔루텍",         market: "KQ", type: "regular" },
  { code: "091120", name: "나우IB Capital",     market: "KQ", type: "regular" },
  { code: "053050", name: "지에스이",           market: "KQ", type: "regular" },
  { code: "086670", name: "비에스씨",           market: "KQ", type: "regular" },
  { code: "048790", name: "비씨카드",           market: "KQ", type: "regular" },
  { code: "210980", name: "SK아이이테크놀로지", market: "KQ", type: "regular" },
  { code: "236360", name: "이마트24",           market: "KQ", type: "regular" },
  { code: "078140", name: "대웅",               market: "KQ", type: "regular" },
  { code: "056080", name: "유진로봇",           market: "KQ", type: "regular" },
  { code: "208140", name: "정다운",             market: "KQ", type: "regular" },
  { code: "042000", name: "카페24",             market: "KQ", type: "regular" },
  { code: "039200", name: "오스코텍",           market: "KQ", type: "regular" },
  { code: "086900", name: "메디오젠",           market: "KQ", type: "regular" },
  { code: "215600", name: "신라젠",             market: "KQ", type: "regular" },
  { code: "141080", name: "레고켐바이오",       market: "KQ", type: "regular" },
  { code: "215200", name: "메가스터디교육",     market: "KQ", type: "regular" },
  { code: "240810", name: "원익IPS",            market: "KQ", type: "regular" },
  { code: "232140", name: "와이씨",             market: "KQ", type: "regular" },
  { code: "290270", name: "유니테스트",         market: "KQ", type: "regular" },
  { code: "096530", name: "씨젠",               market: "KQ", type: "regular" },
  { code: "005290", name: "동진쎄미켐",         market: "KQ", type: "regular" },
  { code: "053800", name: "안랩",               market: "KQ", type: "regular" },
  { code: "064440", name: "이지바이오",         market: "KQ", type: "regular" },
  { code: "166090", name: "하나머티리얼즈",     market: "KQ", type: "regular" },
  { code: "085660", name: "차바이오텍",         market: "KQ", type: "regular" },
  { code: "078160", name: "메가엠디",           market: "KQ", type: "regular" },
  { code: "048410", name: "현대바이오",         market: "KQ", type: "regular" },
  { code: "095500", name: "미래나노텍",         market: "KQ", type: "regular" },
  { code: "033290", name: "코웰패션",           market: "KQ", type: "regular" },
  { code: "041190", name: "우리기술",           market: "KQ", type: "regular" },
  { code: "187220", name: "디케이티",           market: "KQ", type: "regular" },
  { code: "084370", name: "유진테크",           market: "KQ", type: "regular" },
  { code: "036620", name: "감성코퍼레이션",     market: "KQ", type: "regular" },
  { code: "302430", name: "이노션",             market: "KQ", type: "regular" },
  { code: "038500", name: "성호전자",           market: "KQ", type: "regular" },
  { code: "099430", name: "바이오플러스",       market: "KQ", type: "regular" },
  { code: "043200", name: "파루",               market: "KQ", type: "regular" },
  { code: "039290", name: "글로벌텍스프리",     market: "KQ", type: "regular" },
  { code: "119850", name: "지엔씨에너지",       market: "KQ", type: "regular" },
  { code: "032680", name: "소프트센",           market: "KQ", type: "regular" },
  { code: "108380", name: "로보티즈",           market: "KQ", type: "regular" },
  { code: "265740", name: "쿠콘",               market: "KQ", type: "regular" },
  { code: "094970", name: "제이엠티",           market: "KQ", type: "regular" },
  { code: "403870", name: "HPSP",               market: "KQ", type: "regular" },
  { code: "340570", name: "원익홀딩스",         market: "KQ", type: "regular" },
  { code: "140910", name: "파세코",             market: "KQ", type: "regular" },
  { code: "380480", name: "코스모신소재",       market: "KQ", type: "regular" },
  { code: "145720", name: "덴티움",             market: "KQ", type: "regular" },
  { code: "189300", name: "인텔리안테크",       market: "KQ", type: "regular" },
  { code: "352820", name: "하이브",             market: "KQ", type: "regular" },
  // 추가 KOSDAQ — 누락 종목 보완
  { code: "032190", name: "다우데이타",         market: "KQ", type: "regular" },
  { code: "079160", name: "CJ CGV",            market: "KQ", type: "regular" },
  { code: "086960", name: "MBC플러스",         market: "KQ", type: "regular" },
  { code: "114090", name: "GKL",               market: "KQ", type: "regular" },
  { code: "161890", name: "한국콜마홀딩스",     market: "KQ", type: "regular" },
  { code: "041190", name: "우리기술",           market: "KQ", type: "regular" },
  { code: "950130", name: "엑스게이트",         market: "KQ", type: "regular" },
  { code: "950170", name: "JTC",               market: "KQ", type: "regular" },
  { code: "049070", name: "인탑스",             market: "KQ", type: "regular" },
  { code: "019570", name: "알에프세미",         market: "KQ", type: "regular" },
  { code: "036810", name: "에프에스티",         market: "KQ", type: "regular" },
  { code: "119860", name: "SK머티리얼즈",       market: "KQ", type: "regular" },
  { code: "011560", name: "세방전지",           market: "KQ", type: "regular" },
  { code: "072950", name: "좋은사람들",         market: "KQ", type: "regular" },
  { code: "040910", name: "아이씨디",           market: "KQ", type: "regular" },
  { code: "217820", name: "이엔드디",           market: "KQ", type: "regular" },
  { code: "010280", name: "아이스크림에듀",     market: "KQ", type: "regular" },
  { code: "126340", name: "비나텍",             market: "KQ", type: "regular" },
  { code: "403870", name: "HPSP",              market: "KQ", type: "regular" },
  { code: "222040", name: "코닉글로리",         market: "KQ", type: "regular" },
  { code: "373220", name: "LG에너지솔루션",     market: "KS", type: "regular" },
  { code: "259960", name: "크래프톤",           market: "KS", type: "regular" },
  { code: "323410", name: "카카오뱅크",         market: "KS", type: "regular" },
  { code: "293490", name: "카카오게임즈",       market: "KQ", type: "regular" },
  { code: "377300", name: "카카오페이",         market: "KS", type: "regular" },

  // ── ETF (KOSPI) ──────────────────────────────────────────────────────────
  { code: "069500", name: "KODEX 200",          market: "KS", type: "etf" },
  { code: "102110", name: "TIGER 200",          market: "KS", type: "etf" },
  { code: "229200", name: "KODEX 코스닥150",    market: "KS", type: "etf" },
  { code: "252670", name: "KODEX 200선물인버스2X", market: "KS", type: "etf" },
  { code: "122630", name: "KODEX 레버리지",     market: "KS", type: "etf" },
  { code: "114800", name: "KODEX 인버스",       market: "KS", type: "etf" },
  { code: "233740", name: "KODEX 코스닥150레버리지", market: "KS", type: "etf" },
  { code: "251340", name: "KODEX 코스닥150인버스", market: "KS", type: "etf" },
  { code: "091160", name: "KODEX 반도체",       market: "KS", type: "etf" },
  { code: "091180", name: "KODEX 자동차",       market: "KS", type: "etf" },
  { code: "139230", name: "TIGER 코스닥150",    market: "KS", type: "etf" },
  { code: "292150", name: "TIGER KBSTAR미국S&P500", market: "KS", type: "etf" },
  { code: "360750", name: "TIGER 미국S&P500",   market: "KS", type: "etf" },
  { code: "381170", name: "KBSTAR 미국나스닥100", market: "KS", type: "etf" },
  { code: "133690", name: "TIGER 미국나스닥100", market: "KS", type: "etf" },
];

// regular + ETF 포함 / preferred(우선주) · spac 제외
export const STOCK_MASTER_FILTERED = STOCK_MASTER.filter(
  (s) => s.type === "regular" || s.type === "etf"
);
